### ISSUE TITLE
Update Mechanismus für PWA

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#104]
Die PWAs updaten sich nicht/kaum

Ansatz?
https://stackoverflow.com/questions/49739438/when-and-how-does-a-pwa-update-itself

**Comment by patrickstecker** [comment]
Also wir haben einen Service Worker und der Cached auch. Das hat Angular jedoch größtenteils selbst gemacht deswegen weiß ich nicht genau was genau der im cache hat und was und ob er es updated. Ich kann mir vorstellen dass wir vlt eine art inital backend call machen, der uns die aktuelle Version den Frontends gibt und diese dann mit der eigenen in der package.json abgleicht und dann den cache neu lädt. Ist nur die Frage wie man das umsetzt, war nur so mein Gedankengang der irgendwie ganz schlau klingt :D

**Comment by patrickstecker** [comment]
Übrigens sehr nah zu #69

**Comment by DavidSchmidt00** [comment]
idk ob ne installierte pwa sich genauso neu laden lässt wie ne website
