### ISSUE TITLE
Snackbar "Sie sind jz eingecheckt" bedeckt abschicken-button

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#108]
Ich finde wir sollten die "Sie sind jz eingecheckt"-Snackbar wegmachen, da sie den Abschicken-Button auf dem Handy bedeckt und auch nicht wirklich informativ ist.

**Comment by nclskfm** [comment]
das is kein bug, sondern ein Feature @DavidSchmidt00  :(

**Comment by DavidSchmidt00** [comment]
soooorry
