### ISSUE TITLE
Umstellung auf Git Flow

### ISSUE THREAD

**Issue by RobSpot-Gaming** [SAKPaaS/frontend#112]
Als Deployment Beauftragter benötige ich sowohl einen Master als auch einen Development Branch. Dies ist nötig um eine "Production Intrgration Umgebung" (siehe [hier](https://github.com/SAKPaaS/deployment/issues/11)) erstellen zu können.

Zukünftiger Ablauf: 
Development Branch -> Dev Umbeung (Abfragen gegen Dev-Backend)
Master Branch -> Prod Int Umgebung (Abfragen gegen Prod-Backend)
Release -> Prod Umgebung (Abfragen gegen Prod-Backend)

**Comment by MrKraboom** [comment]
Git flow würde sich hierfür eignen

**Comment by nclskfm** [comment]
Nachdem Pullrequest _#111 general improvements_.
