### ISSUE TITLE
NotifictionService implementieren

### ISSUE THREAD

**Issue by timgrohmann** [SAKPaaS/frontend#15]
Snackbar für Benachrichtigungen

**Comment by nclskfm** [comment]
@timgrohmann  @patrickstecker 
um den Notificationservice anzuwenden, einfach den `SnackBarService` einbinden und eine Notification senden:
```
this.snackBarService.sendNotification({
          message: 'Das hat leider nicht geklappt! Bitte versuche es erneut.',
          type: SnackBarTypes.ERROR
        });
```

SnackBarTypes kann entweder SUCCESS oder ERROR sein.
