### ISSUE TITLE
Bugfixes Texte

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#220]
Ich als User möchte immer die richtigen Texte sehen. Manchmal sind diese beim laden der Seite nicht richtig da.

Bei “unbekannte auslastung“ gibt es anscheinend keine Übersetzung.

**Comment by patrickstecker** [comment]
Die Übersetzung ist da. Das Problem ist, dass wenn die Locations einmal geladen sind in der Liste, und der Nutzer die Sprache dann ändert, die Occupancy Reports nicht mehr geändert werden.
