### ISSUE TITLE
Anzeige der kürzlichen Occupancy-Reports

### ISSUE THREAD

**Issue by RobSpot-Gaming** [SAKPaaS/frontend#37]
Anzeige, wie viele Occupancy-Reports in der letzen Stunde (oder zwei) eingereicht wurden.

**Comment by DavidSchmidt00** [comment]
zunächst muss #70 umgesetzt werden, da sind die daten drin

**Comment by DavidSchmidt00** [comment]
Done with:
https://github.com/SAKPaaS/backend/pull/48

**Comment by DavidSchmidt00** [comment]
Damit wird zurüclgegeben:
- auf wievielen Reports die Occupancy beruht
- wann der letzte Report rein kam auf dem die Occupancy beruht
