### ISSUE TITLE
Adminseite für Marktpersonal

### ISSUE THREAD

**Issue by timgrohmann** [SAKPaaS/frontend#4]
Ich als Marktmitarbeiter möchte administrativ über die Auslastung in meinem Markt bestimmen können.

**Akzeptanzkriterien**
- SMler sieht seinen eigenen Markt
- SMler kann Auslastung angeben

**Comment by DavidSchmidt00** [comment]
Dazu gehört auch ein Verifizierungsprozess für Marktleiter/Personal
