### ISSUE TITLE
ddos abwehren

### ISSUE THREAD

**Issue by nclskfm** [SAKPaaS/frontend#43]

**Comment by DavidSchmidt00** [comment]
Ist das nicht eher backend? 😄

**Comment by MrKraboom** [comment]
Sehe ich auch so, Frontend müsste aber vielleicht zumindest einen random client token mitschicken, damit man wenigstens etwas anfangen kann.

**Comment by nclskfm** [comment]
Ja, hab das gestern nur noch schnell aufgeschrieben und nicht mehr so viel drüber nachgedacht. Hat aber eine relativ hohe prio imo. Is nicht so schwer den Server abzuschießen :D 

Vielleicht im frontend auch n captcha. Kann ja mal drüber nachdenken später

**Comment by DavidSchmidt00** [comment]
Gibts eine Free Version von Cloudflare oder so?

**Comment by DavidSchmidt00** [comment]
Chapta find ich jetzt per se net so sinnvoll

**Comment by MrKraboom** [comment]
Ich glaube DDoS ist auch nicht wirklich das Problem, sondern eher Spamming. Das könnte aber eher die Aufgabe des Backends sein. Ich eröffne da mal ein Issue.

**Comment by DavidSchmidt00** [comment]
Ok dann close ich das hier mal.
neues issue backend/#38
