### ISSUE TITLE
Erneutes GPS-Zugriff erlauben

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#47]
Wenn man einmal den GPS-Zugriff abgelehnt hat, kommt das nicht nochmal.

**Comment by timgrohmann** [comment]
Das geht leider nicht (https://stackoverflow.com/questions/20678707/ask-for-geolocation-permission-again-if-it-was-denied)
Anstelle habe ich sinnvolles Error-Handling hinzugefügt und werde vor der Frage nach der Location ein Disclaimer a la "Wenn du nicht ja drückst dann ist halt kacke" machen.
