### ISSUE TITLE
Erneut fragen, ob PWA hinzugefügt werden soll.

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#48]
Da kaum jemand PWA's kennt, wird das jeder beim erstem Mal ablehnen.

Die Aufforderung muss mehrmals kommen.

**Comment by timgrohmann** [comment]
Joo also das geht so auch nicht. (Das B in Browser steht für Bitch)

Die einzige Option ist, später zu Fragen. https://web.dev/customize-install/

**Comment by DavidSchmidt00** [comment]
Ja, fänd ich besser als den User einfach ohne Vorwarnung zu fragen.

Ist es möglich das nach einer bestimmten Zeit (vlt. 20 Sekunden) zu fragen?

**Comment by patrickstecker** [comment]
Bestimmt

**Comment by patrickstecker** [comment]
Ich hab mich dran versucht und aufgegeben, have fun Tim 😂

**Comment by DavidSchmidt00** [comment]
I think Tim ist schon daran am arbeiten

**Comment by DavidSchmidt00** [comment]
@timgrohmann Meinte er konnte das Event abfangen? Können wir das dann nach 20 sec oder so abfeuern?
