### ISSUE TITLE
SEO für Websites

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#49]
Die Websites sollten so optimiert werden, dass sie von Suchmaschinen besser gefunden werden können.

**Comment by DavidSchmidt00** [comment]
![image](https://user-images.githubusercontent.com/43894937/78032710-bc85d500-7365-11ea-8945-e1cc0687d681.png)

**Comment by DavidSchmidt00** [comment]
Aktuell findet man happyhamster garnicht ohne "happyhamster org" einzugeben.

Die Untertitel sind auch seeehr suboptimal ^^

**Comment by DavidSchmidt00** [comment]
@timgrohmann du meintest du kannst dich drum kümmern oder?^^

**Comment by timgrohmann** [comment]
`true`

**Comment by timgrohmann** [comment]
Hab das mehr oder minder nebenbei gefixt, das einzige, was man laut Google da machen kann, ist einen Meta-Description-Tag hinzuzufügen.
Des habsch jemacht, jetza müssema nu uff Google wartne. Schöner Tag.

**Comment by nclskfm** [comment]
Hä wo hast du die Änderungen gemacht? :D
@timgrohmann

**Comment by DavidSchmidt00** [comment]
Ich seh auch nix ^^

**Comment by timgrohmann** [comment]
Hab ich vorhin auf master commited😂😂

**Comment by nclskfm** [comment]
Achso da unten, jetzt hab ichs gesehen 😂
