### ISSUE TITLE
Suchfunktion erweitern

### ISSUE THREAD

**Issue by nclskfm** [SAKPaaS/frontend#51]
von slack kam der Kommentar: 
"PLZ Suche ging bei mir nicht - da habe ich auf Andoid einen frozen Screen bekommen"

1) Fehler reproduzierbar?
2) kommunizieren, dass atm nur name durchsucht wird

**Comment by DavidSchmidt00** [comment]
Über die Suchleiste soll man auch PLZ (und Ort) suchen können.

Dazu wird vom @SAKPaaS/backend ein neuer API-Endpoint angelegt.

**Comment by DavidSchmidt00** [comment]
@SAKPaaS/frontend Wollt ihr dann aus dem Backend zu einer PLZ die GPS-Koordinaten haben?

**Comment by DavidSchmidt00** [comment]
Backend Issue: https://github.com/SAKPaaS/backend/issues/54
