### ISSUE TITLE
Entfernung in Suche anzeigen

### ISSUE THREAD

**Issue by MrKraboom** [SAKPaaS/frontend#57]
Ich als Benutzer möchte die vorgeschlagnen Supermärkte gerne so vorgeschlagen bekommen, dass der nächste Supermarkt oben in der Liste angezeigt wird.
Außerdem möchte ich die Entfernung zu diesem Supermarkt wissen, da ich sonst nicht intuitiv weiß, wonach diese Liste sortiert ist.

**Comment by DavidSchmidt00** [comment]
Sollte der Meinung von @SAKPaaS/backend nach vom Frontend gelöst werden, da wir im Backend ja nur wissen, welcher Punkt auf der Karte zentriert ist und nicht wo der Nutzer gerade ist.

Berechnung der Luftlinie ist aber sehr sehr einfach.
