### ISSUE TITLE
Auslastungs-Seite wieder schließen können

### ISSUE THREAD

**Issue by timgrohmann** [SAKPaaS/frontend#61]
Nach dem Check-In kann aktuell die Auslastungs-Seite nicht mehr geschlossen werden.
Dies sollte geändert werden.

**Comment by nclskfm** [comment]
will man das? :D

**Comment by MrKraboom** [comment]
Vielleicht Abbrechen wenn man ausversehen drauf geklickt hat? Dann sollte aber auch der Check-in nicht abgeschickt werden

**Comment by nclskfm** [comment]
@MrKraboom Dann brauchen wir aber ein manuelles checkOut. Weil das checkIn wird bevor man auf die Seite kommt abgeschickt.

**Comment by MrKraboom** [comment]
@nclskfm Oder das Check-in erst mit der Schätzung schicken?

**Comment by nclskfm** [comment]
hmm kann man machen, is dann aber semi geil. Dann könnt ihr mich auch einchecken, wenn n Occupancy gesendet wird, und der user WEB_APP ist...

**Comment by nclskfm** [comment]
Also das finde ich uncool.
Also ich würde nachher erstmal ein "ich bin doch nicht hier"-Button machen, Wenn ihr wollt, macht im Backend noch ein checkOut Endpoint, damit man die eine Person wieder zurück nehmen kann. Oder ob man den einen Nutzer einfach vernachlässigt...

**Comment by MrKraboom** [comment]
Hmm da finde ich die Lösung das Occupency zu verwenden eigentlich am besten. Check-in macht ja nichts außer zählen, das kann man aber auch mit occupancy.
Check-in hat nur wirklich Sinn ergeben als wir Check-out noch hatten.

Ergo: Check-in endpoint entfernen? Was meint ihr? @RobSpot-Gaming @DavidSchmidt00

**Comment by DavidSchmidt00** [comment]
Also entfernen würd ich den net, um perspektivisch Personenzähler auf IoT Basis umsetzten zu können.

**Comment by nclskfm** [comment]
checkIn fliegt raus
