### ISSUE TITLE
Jump to Id funktioniert am Handy nicht

### ISSUE THREAD

**Issue by nclskfm** [SAKPaaS/frontend#66]
Am Handy springt er nicht zum Supermarkt nach einem Report

**Comment by DavidSchmidt00** [comment]
@nclskfm Bei mir funktionierts 🤔

**Comment by nclskfm** [comment]
Ahjo, wurde mit Release 1.4.5 gefixt. Mein Handy hatte jedoch noch die alten Dateien im Cache. 🙄
