### ISSUE TITLE
Content localization

### ISSUE THREAD

**Issue by elsholz** [SAKPaaS/frontend#67]
Create different locales. This is not necessary for most of our users, but it is important if we want to get funding from any international institution.

**Comment by elsholz** [comment]
Maybe give the language as a query parameter and save it as a variable, such that the site can determine which content to display given the locale as the key.

**Comment by DavidSchmidt00** [comment]
Du kannst hier ruhig deutsch schreiben :D

**Comment by DavidSchmidt00** [comment]
Ich versteh die Frage garnicht

**Comment by timgrohmann** [comment]
Wir sind ein DEUTSCHES Projekt. lol

**Comment by MrKraboom** [comment]
@timgrohmann Sagst du und schreibst selbst Englische Tickets 😂
Bin aber der Meinung das localization kommen sollte, damit wir expandieren können

**Comment by timgrohmann** [comment]
Es ging mir primär darum, dass das Produkt aktuell nur in DE funktioniert und das aktuell unser Scope ist xD

**Comment by elsholz** [comment]
Es spricht aber nicht jeder der in Deutschland wohnt auch unbedingt deutsch

**Comment by nclskfm** [comment]
Ich hab jetzt damit angefangen. Die verschiedenen Sprachen werden jeweils in einer json gespeichert, so dass es beliebig erweiterbar ist.
Aktuell wird es sich wohl erstmal auf Englisch und Deutsch beschränken. Wenn mir jemand bei den JSONs helfen will, kann er/sie sich gerne melden :D

**Comment by DavidSchmidt00** [comment]
Kann gern helfen, schreib einfach auf Discord

**Comment by nclskfm** [comment]
Released. 🎏
