### ISSUE TITLE
Locations Abfrage begrenzen

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#68]
Es sollten nur Locations für den Kartenbereich angezeigt werden, der auch sichtbar ist.
Dafür brauchen wir doch wieder einen "Radius" in der API.

**Comment by timgrohmann** [comment]
Wir hatten schon einen Radius in der API und uns dann dagegen entschieden xD

**Comment by MrKraboom** [comment]
We have gone full circle!

**Comment by DavidSchmidt00** [comment]
Man bekommt jetzt nur noch maximal 100 Locations um den Mittelpunkt. Wurde im backend gefixed.
