### ISSUE TITLE
Hardreload bei neuer Version

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#69]
Zitat Patrick:
Ich glaube es wäre cool wenn wir einen cookie setzen mit der version und die immer abgleichen beim aufrufen der seite. Wenn die version veraltet ist löschen wir den cache. Dann muss der user das nicht manuell machen

**Comment by nclskfm** [comment]
Wie wollen wir die Versionsnummer mitgeben? Eine neue API, die am Anfang einmal aufgerufen wird zum abgleichen der Version im Cache? @SAKPaaS/backend 

Ein "harten" Reload sollte kein Problem sein, dass kann man einfach forcen mit `location.reload(true)`

**Comment by DavidSchmidt00** [comment]
Fänd ich jz unschön dafür nen neuen Endpunkt zu machen...

**Comment by MrKraboom** [comment]
Löscht `location.reload(true)` auch den cache? @nclskfm

**Comment by MrKraboom** [comment]
Ich würde vorschlagen dass wir eine `config.json` im root Verzeichnis vom `frontend` ablegen, dort steht dann der `commit hash` drin, sowie die `API URL`, dann können wir auch einfach verschiedene Environments anlegen. @DavidSchmidt00

**Comment by DavidSchmidt00** [comment]
Wenn das der gesellschaftlich aktzeptierte Weg ist, gerne🤷🏼‍♂️😂

**Comment by nclskfm** [comment]
@MrKraboom 
> Location.reload()
> Reloads the resource from the current URL. Its optional unique parameter is a Boolean, which, when it is true, causes the page to always be reloaded from the server. If it is false or not specified, the browser may reload the page from its cache.

**Comment by nclskfm** [comment]
> Ich würde vorschlagen dass wir eine `config.json` im root Verzeichnis vom `frontend` ablegen, dort steht dann der `commit hash` drin, sowie die `API URL`, dann können wir auch einfach verschiedene Environments anlegen. @DavidSchmidt00

Aber  das löst doch nicht das oben genannte Problem oder? Wir müssen die Version vom Client ja irgendwie mit der aktuellen abgleichen...

**Comment by MrKraboom** [comment]
@nclskfm Nur die `index.html` oder auch die ganzen anderen Datein?

**Comment by MrKraboom** [comment]
@nclskfm Man muss natürlich die Version der aktuell geladenen Seite im Browser Speicher speichern und dann mit der `config.json` abgleichen. Ins Backend soll es aufjeden Fall nicht, da das Backend ja nichts mit der Version des Frontends zu tun hat.

**Comment by nclskfm** [comment]
> @nclskfm Nur die `index.html` oder auch die ganzen anderen Datein?

Bin ich mir nicht sicher, aber ich vermute mal den gesamten cache. Müsste man mal ausprobieren.

**Comment by patrickstecker** [comment]
Ich würde auch den gesamten cache leeren, ist am sichersten, wer weiß was später noch dazu kommt.
Ich weiß aber auch nicht ob dann die config.json gecached wird. Das wäre halt blöd 😂

**Comment by MrKraboom** [comment]
Die `config.json` könnte man mit "nicht-cachen" Headern senden.
