### ISSUE TITLE
Datenmodelle der neuen openAPI Definition Anpassen

### ISSUE THREAD

**Issue by MrKraboom** [SAKPaaS/frontend#70]
https://app.swaggerhub.com/apis/SAKPaaS/SAKPaaS/1.0.0

Backend Issue: SAKPaaS/backend#46
Backend Pullrequest: SAKPaaS/backend#48

*WICHTIG!* Die beiden Pullrequests müssen gleichzeitig released werden!

**Comment by DavidSchmidt00** [comment]
Geht live mit:
https://github.com/SAKPaaS/backend/pull/48

Releases müssen gleichzeitig sein!!!
