### ISSUE TITLE
2 Abfragen?

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#74]
Kann es sein, dass bei jedem Bewegen der Karte 2 Abfragen gemacht werden?

**Comment by DavidSchmidt00** [comment]
![image](https://user-images.githubusercontent.com/43894937/77583867-14de5200-6ee2-11ea-9a44-c3792a263dcc.png)

**Comment by nclskfm** [comment]
Ich denke, dass ist ganz normal. Der Service Worker requested die Location unabhängig vom Main thread.
https://github.com/angular/mobile-toolkit/issues/186
> On the first start of PWA you do this double job: you app (index.html) is loading assets (to render the app for the user), and your service worker is loading the same assets (to cache them for the future use)
On the next starts of PWA your app is still requesting the assets (as regular), but now thanks to SW you can serve the responses from the cache (it's up to your SW logic).

Man müsste mal schauen, ob man das umkonfigurieren kann, da der SW an sich nichts (oder zu mindestens zum jetzigen Stand nichts) mit der Applogik (also zb mit den Locations) zutun hat. @patrickstecker

**Comment by DavidSchmidt00** [comment]
Also lässt sich das nicht fixen?

**Comment by nclskfm** [comment]
Ich wüsste spontan nicht wie, müsste @patrickstecker was zu sagen^^

**Comment by timgrohmann** [comment]
War eine Fehlinterpretation der Dev-Tools.
