### ISSUE TITLE
Bereits früher Locations anzeigen

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#75]
Ich finde die Locations sollten auch schon ab einer geringen Zoomstufe angezeigt werden.
Aufm Land ist das sonst blöd

**Comment by nclskfm** [comment]
Ich würde das Minimumlevel auch ein bisschen verringern.

**Comment by DavidSchmidt00** [comment]
Team-Entscheidung: Ein tick früher anzeigen
