### ISSUE TITLE
Cookie Hinweis

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#80]
Wir benötigen einen Cookie-Hinweis.

Frage: 
Nur Hinweis (Risiko: hoch) 
oder 
Einwilligung und vorher nichts speichern (Risiko: gering)

https://www.e-recht24.de/artikel/datenschutz/8451-hinweispflicht-fuer-cookies.html

**Comment by nclskfm** [comment]
Ich würde es so machen, dass wir beim initialisieren der App schauen, ob ein cookie (irgendwie "ALLOW_COOKIES" oder so) existiert. Wenn er existiert passiert nichts, falls er nicht existiert, fragen wir nach und speichern ihr eventuell.

Alle anderen Cookies schauen zu erst, ob der ALLOW_COOKIES-Cookie existiert, ansonsten, speichern sie halt nichts.

**Comment by nclskfm** [comment]
fixed und in master gepusht.
