### ISSUE TITLE
OSM: Tiles zu Vector Grafiken

### ISSUE THREAD

**Issue by MrKraboom** [SAKPaaS/frontend#82]
Als Mobile-Nutzer möchte ich eine möglichst kleine Datenmenge herunterladen. Deswegen möchte ich nicht, dass Bilder, sondern nur Vektor-Daten heruntergeladen werden.

Als Nutzer möchte ich eine möglichst schöne Erfahrung haben, deswegen hätte ich gerne Karten die einen schönen Style haben.

**Comment by MrKraboom** [comment]
Ist das Grundsätzlich möglich?

**Comment by timgrohmann** [comment]
Grundsätzlich möglich, ich habe es gerade mal hiermit ausprobiert:
https://github.com/openlayers/ol-mapbox-style#stylefunction
https://openmaptiles.org/

Das ist so unendlich unperformant… Auf meinem Laptop hat's so 10 FPS maximal. Erstmal won't fix.
