### ISSUE TITLE
Wenn vom Impressum wieder auf die App geleitet wird, zoomt er nicht mehr 

### ISSUE THREAD

**Issue by nclskfm** [SAKPaaS/frontend#84]
after #73

**Comment by patrickstecker** [comment]
Kann ich nicht nachproduzieren im Branch von #73

**Comment by nclskfm** [comment]
Hab das Problem identifiziert:
im gpsService werden die Koordinaten als BehaviorSubject gespeichert. Und er zoomt initial nur, wenn die Koordinaten `fromDevice===true` sind. Der letzte Wert, der im BehaviorSubject gespeichert wird, ist aber nicht vom Device, daher zoom er nicht.

**Comment by nclskfm** [comment]
Hab das Ticket nach jira verschoben: https://pw-netz.atlassian.net/browse/TINF-105
