### ISSUE TITLE
Hilfe Button

### ISSUE THREAD

**Issue by RobSpot-Gaming** [SAKPaaS/frontend#86]

**Comment by makr173** [comment]
Der Hilfe Button soll auf der Karte angezeigt sein und auf die Erklärseite https://welcome.happyhamster.org/ führen.

**Comment by nclskfm** [comment]
Ist das nicht die Funktion von "über uns"?

**Comment by patrickstecker** [comment]
@nclskfm Ja aber es war in Diskussion, dass Menschen die wissen wollen wie HappyHamster Funktioniert nicht auf "über uns" drücken, weil das eher wie eine Vorstellung des Teams oder Projekts klingt und nicht wie eine Anleitung. Jetzt ist die Frage ob wir einen neuen Button machen oder "über und" einfach in "Hilfe" umbenennen oder zu nen Fragezeichen Icon oder whatever
