### ISSUE TITLE
Vorschlag bei App-Start und GPS -> Bist du gerade hier?

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/frontend#89]
Joost meinte es wäre nice, wenn man beim App-Start einen Vorschlag bekäme, falls man nah genug an einem Supermarkt ist, ob man gerade da ist.
Dann müsste man nicht durch paar Märkte klicken um den zu finden vor dem man gerade steht.

**Comment by patrickstecker** [comment]
Sehr gute Idee. Wie wäre das Style technisch am besten umzusetzen? Mit so ner Art pop-up oder eher nen bottom sheet?

**Comment by DavidSchmidt00** [comment]
Um alles einheitlich zu halten, würde ich erstmal sidney bitte, das in zeplin zu designen.
